apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - db-deployment.yaml
  - db-service.yaml
  - namespaces.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - result-deployment.yaml
  - result-service.yaml
  - results-ingress.yaml
  - vote-deployment.yaml
  - vote-service.yaml
  - voting-ingress.yaml
  - worker-deployment.yaml
