apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/Kvng-Pray/HomeLab.git
    path: apps/argocd
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
